home_page/home/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<username>\w+)/$', views.IndexView.as_view(), name="user"),
    url(r'^(?P<username>\w+)/skills/$',
        views.SkillsListView.as_view(), name="skills")
]

home_page/home_page/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from home import views


urlpatterns = patterns(
    '',
    url(r'^$', views.RedirectView.as_view(), name='home_redirect'),
    url(r'^u/', include('home.urls', namespace="home")),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +\
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_page/home/models.py
from datetime import date
from dateutil.relativedelta import relativedelta
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    user = models.ForeignKey(User)
    birth = models.DateField()
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    pic = models.ImageField(upload_to="pics/", blank=True)

    def get_age(self):
        return relativedelta(date.today(), self.birth).years

    def __str__(self):
        return "{}. {} profile".format(self.user.first_name[:1],
                                       self.user.last_name)


class Skill(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=30)
    description = models.TextField(blank=True)
    level = models.IntegerField(default=0,
                                help_text="A value between 0 and 100.")
    from_date = models.DateField()

    def __str__(self):
        return "{} skill for {}".format(self.name, self.user)

    class Meta:
        ordering = ["level"]


class SocialLink(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=20)
    url = models.URLField()

    def __str__(self):
        return "{} link for {}".format(self.name.title(),
                                       self.user.username)

home_page/home/views.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, RedirectView

from .models import Skill, SocialLink, UserProfile


class RedirectView(RedirectView):
    permanent = False
    url = reverse_lazy("home:user", kwargs={"username": "xbello"})


class IndexView(DetailView):
    model = UserProfile
    slug_field = "user__username"
    slug_url_kwarg = "username"
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = {}

        if self.object:
            context["social_links"] = \
                {_.name: _ for _ in SocialLink.objects.filter(
                    user=self.object.user)}
            context["user"] = self.object.user

        context.update(kwargs)

        return super().get_context_data(**context)

    def get_queryset(self):
        qs = super().get_queryset().select_related("user")

        return qs


class SkillsListView(ListView):

    """View to the Skills of an user."""

    model = Skill
    template_name = "skill_list.html"

    def get_context_data(self, **kwargs):
        context = {}

        context["user"] = get_object_or_404(
            User, username=self.kwargs.get("username"))

        context.update(kwargs)

        return super().get_context_data(**context)

    def get_queryset(self):
        qs = super().get_queryset().select_related("user")

        return qs.filter(user__username=self.kwargs["username"])

home_page/home/templates/index.html
{% extends "top_bar.html" %}
{% load static from staticfiles %}

{% block page_content %}
 <div class="panel panel-default">
  <div class="panel-heading">
   <h1 class="panel-title"><strong>Hi! I'm {{ userprofile.user.first_name }}</strong></h1>
  </div>
  <div class="panel-body">
   <div class="media">
    <div class="media-body">
     <dl>
      <dt>Age</dt>
      <dd>{{ userprofile.get_age }}</dd>
      <dt>Address</dt>
      <dd>{{ userprofile.address }}</dd>
      <dt>e-mail</dt>
      <dd>{{ userprofile.user.email }}</dd>
      <dt>Phone</dt>
      <dd>{{ userprofile.phone }}</dd>
     <dl>
    </div>
    <div class="media-right">
     <div class="media-object">
      <img src="{% if userprofile.pic %}{% static userprofile.pic.url %}{% else %}{% static "img/anonymous.png" %}{% endif %}" class="media-heading img-circle hidden-xs" style="width: 128px; height: 128px;">
      <img src="{% if userprofile.pic %}{% static userprofile.pic.url %}{% else %}{% static "img/anonymous.png" %}{% endif %}" class="media-heading img-circle visible-xs" style="width: 48px; height: 48px;">
     </div>
    </div>
   </div>
  </div>
  {% include "social_footer.html" %}
 </div>
{% endblock page_content %}

home_page/home/templates/skill_list.html
{% extends "top_bar.html" %}
{% load staticfiles %}

{% block page_content %}
 <div class="panel panel-default">
  <div class="panel-body">
  {% for object in object_list %}
   <div class="progress">
    <div class="progress-bar" role="progressbar" style="width: {{ object.level }}%;">
     {{ object.name }} since {{ object.from_date }}
    </div>
   </div>
  {% endfor %}
  </div>
 </div>
{% endblock page_content %}

home_page/home/templates/social_footer.html
{% load fontawesome %} 

<div id="social-bar" class="panel-footer center-block">
 <a href="{{ social_links.github.url }}" target="_blank">{% fontawesome_icon 'github' color='#333333' large=True %}</a>
 <a href="{{ social_links.googleplus.url }}" target="_blank">{% fontawesome_icon 'google-plus' color='#E14107' large=True %}</a>
 <a href="{{ social_links.stackoverflow.url }}" target="_blank">{% fontawesome_icon 'stack-overflow' color='#FC9A24' large=True %}</a>
 <a href="{{ social_links.linkedin.url }}" target="_blank">{% fontawesome_icon 'linkedin' color='#006FA6' large=True %}</a>
 <a href="{{ social_links.researchgate.url }}" target="_blank"><i class="ai ai-researchgate ai-lg" style="color:#36A493" ></i></a>
 <a href="{{ social_links.orcid.url }}" target="_blank"><i class="ai ai-orcid ai-lg" style="color:#A6CE39" ></i></a>

</div>

home_page/home/templates/top_bar.html
{% extends "dh5bp/base.html" %}
{% load bootstrap3 %}
{% load fontawesome %}
{% load static from staticfiles %}

{% block head %}
 <link rel="icon" type="image/x-icon" href="{% static "img/favicon.ico" %}" />
 <link rel="stylesheet" href="{% static "css/main.css" %}" />
 <link rel="stylesheet" href="{% static "css/academicons.min.css" %}" />
 {% bootstrap_css %}
 {% fontawesome_stylesheet %}

 {# Display django.contrib.messages as Bootstrap alerts #}
 {# {% bootstrap_messages %} #}
{% endblock head %}

{% block title %}X. Bello home page{% endblock %}

{% block content %}
 {% block topbar %}
  <nav class="navbar navbar-inverse">
   <div class="container-fluid">
    <div class="navbar-header">
     {# These are the three lines button #}
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
       <span class="sr-only"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>

     <a class="navbar-brand" href="{% url "home_redirect" %}">{{ user.first_name }} {{ user.last_name }}</a>
    </div>

    <div class="collapse navbar-collapse" id="navbar">
     <ul class="nav navbar-nav">
      <li><a href="{% url "home:skills" username=user.username %}">{% fontawesome_icon 'mortar-board' large=True %} Skills</a></li>
      <li><a href="#">{% fontawesome_icon 'wrench' large=True %} Experience</a></li>
      <li><a href="#">{% fontawesome_icon 'book' large=True %} Blog</a></li>
      <li><a href="#">{% fontawesome_icon 'envelope' large=True %} Contact</a></li>
     </ul>
    </div>
   </div>
  </nav>
 {% endblock topbar %}
 <div class="page_wrapper">
  <div class="row">
   {% block page_content %}{% endblock %}
  </div>
 </div>
{% endblock content %}

{% block post_main_script %}
 {% bootstrap_javascript %}
{% endblock %}